### ISSUE TITLE
Could the dependencies be updated?

### ISSUE THREAD

**Issue by jacoswarts** [akash-joshi/gatsby-query-params#24]
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.1" from the root project

**Comment by akash-joshi** [comment]
I've tried (and most likely failed) to update the dependencies. Can you have a look and let me know if there's anything specific you need updated?

**Comment by productiveme** [comment]
You can close the issue, I've forgotten which the problematic package was at the time
