### ISSUE TITLE
document is undefined

### ISSUE THREAD

**Issue by rj-coding** [akash-joshi/gatsby-query-params#3]
This plugin doesn't work, because it assumes that document is present during static rendering.

**Comment by akash-joshi** [comment]
Can you please share a code sample? Thanks

**Comment by rj-coding** [comment]
Hi, sure no problem.

It happens when you use your own example in _any_ page in /pages or /template when running `gatsby build`.

So, here is the minimal example:
```
import * as React from 'react'

// @ts-ignore
import { useQueryParam, getSearchParams } from "gatsby-query-params";

const QueryParamsError : React.FunctionComponent = () => {
  return <p>{JSON.stringify(getSearchParams()) }</p>
}

export default QueryParamsError;
```

And now run `gatsby build` and you get:

```
failed Building static HTML for pages - 0.948s

 ERROR #95312 

"document" is not available during server side rendering.

See our docs page for more info on this error: https://gatsby.dev/debug-html


   7 |   useEffect(() => {
   8 |     setSearch(document.location.search ? queryString.parse(document.location.search) : {})
>  9 |   }, [document.location.search])
     |       ^
  10 |   
  11 |   return searchParams;
  12 | }


  WebpackError: ReferenceError: document is not defined
```

So, you need to check if `document` is defined, like this:
```
const getSearchParams = () => {
  const [searchParams, setSearch] = useState({})
  const inBrowser = typeof document !== 'undefined'

  useEffect(() => {
    if (inBrowser) {
      setSearch(document.location.search ? queryString.parse(document.location.search) : {})
    }
  }, inBrowser ? [document.location.search] : [])

  return searchParams
}
```

**Comment by Nahani** [comment]
same issue

**Comment by rj-coding** [comment]
> same issue

Did you have the same issue when using my fix above? Because that works for me.

However, I don't have the feeling the author of the plugin has time or is interested.

**Comment by Nahani** [comment]
Yes with your fix it's works thank you !

**Comment by akash-joshi** [comment]
Hey @rj-coding thanks for your code sample and @Gomez for the PR. I understand I have the responsibility of maintaining this library. Will have a look to make sure the PR is working right and make a push tomorrow. Again, thanks to you all for trying my plugin.

**Comment by akash-joshi** [comment]
PR checks out. Thanks @Gomez
